# Generated by Django 4.2.11 on 2024-03-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.PositiveBigIntegerField(null=True, verbose_name='contact number'),
        ),
    ]
