# Generated by Django 4.2.11 on 2024-03-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='contact number'),
        ),
    ]
